# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"

    filter_sets:

        trick_thumbnail:
            filters:
                thumbnail:
                    size:          [270, 200]
                    mode:          outbound
                    allow_upscale: true
